### ISSUE TITLE
hibernate.default_schema don't work for sequences

### ISSUE THREAD

**Issue by guy1699** [hibernate/hibernate-reactive#1120]
When saving with `session.persist(entity)` I get an error saying the sequence (that set the serial PK for PostgreSQL DB) does not exists.

If I have this sequence in the public schema it does find it, so I know the issue is that selecting a sequence does not consider the schema configured by hibernate.default_schema.

If I update a record it will update correctly in the right schema.

```
@Entity
@Table(name = "tenants")
public class Tenant extends AbstractAdminOLTPEntity {

    @Id
    @SequenceGenerator(name="tenants_id_seq" , allocationSize=1)
    @GeneratedValue(strategy= GenerationType.SEQUENCE, generator="tenants_id_seq")
    @Column(name = "id")
    private Long id;
```

**Comment by DavideD** [comment]
Can you show us how you've mapped the entity property that uses the sequence, please?

**Comment by guy1699** [comment]
I don't know how but it is working after playing around with all kinds of things in the local PostgreSQL.
But the problem was there as I describe it.

```

@Entity
@Table(name = "tenants")
public class Tenant extends AbstractAdminOLTPEntity {

    @Id
    @SequenceGenerator(name="tenants_id_seq" , allocationSize=1)
    @GeneratedValue(strategy= GenerationType.SEQUENCE, generator="tenants_id_seq")
    @Column(name = "id")
    private Long id;
```

**Comment by guy1699** [comment]
@DavideD Did you find a bug or did you just throw it to the next milestone and investigate later?
Do you have idea for workaround?

**Comment by DavideD** [comment]
I've just label it and assigned it to myself so that I don't forget about it, but I haven't had time to look into this yet.
I will try to create a test this week.

As a workaround, you can try to set the attribute `schema` or `catalog` in `@SquenceGenerator`:

```
@SequenceGenerator(schema = "your_schema", ...)
```

**Comment by gavinking** [comment]
Fixed.

**Comment by yrodiere** [comment]
Hey @gavinking @DavideD, FYI we have a claim in Quarkus [here](https://github.com/quarkusio/quarkus/issues/31926) that this wasn't fixed. It would seem that calls to `nextval` do not mention the default schema in Quarkus.

Note that in order for default schema/catalog to work in Quarkus, they need to be generated late (basically at `SessionFactory` initialization), using a `SqlStringGenerationContext` , which would be a good practice for all generated SQL anyway. For ID generators in Hibernate ORM (don't know about reactive), that would mean generating SQL in `org.hibernate.id.IdentifierGenerator#initialize` (and definitely *not* in `org.hibernate.id.IdentifierGenerator#configure`).

**Comment by DavideD** [comment]
Everything seems to work fine to me.
We test this via [SequenceGeneratorDefaultSchemaTest](https://github.com/hibernate/hibernate-reactive/blob/f17e8a1e80c70329baaf3d98fc7f229bf68b02e7/hibernate-reactive-core/src/test/java/org/hibernate/reactive/SequenceGeneratorTest.java#L75) and this is the log:
```
[Hibernate] create schema hr
[Hibernate] create sequence hr.test_id_seq start with 5 increment by 1
[Hibernate] create table hr.SequenceId (id integer not null, version integer, string varchar(255), primary key (id))

[Hibernate] select nextval('hr.test_id_seq')

[Hibernate] insert into hr.SequenceId (string,version,id) values ($1,$2,$3)
[Hibernate] select s1_0.id,s1_0.string,s1_0.version from hr.SequenceId s1_0 where s1_0.id=$1
[Hibernate] update hr.SequenceId set string=$1,version=$2 where id=$3 and version=$4
[Hibernate] select s1_0.id,s1_0.string,s1_0.version from hr.SequenceId s1_0 where s1_0.id=$1
[Hibernate] select s1_0.id,s1_0.string,s1_0.version from hr.SequenceId s1_0
[Hibernate] delete from hr.SequenceId where id=$1 and version=$2
```

This is the entity:
```
        @Entity(name = "SequenceId")
	@SequenceGenerator(name = "seq", sequenceName = "test_id_seq", initialValue = 5, allocationSize = 1)
	@Table(name = "SequenceId")
	public static class SequenceId {
		@Id
		@GeneratedValue(generator = "seq")
		Integer id;
       ...
       }
```
It seems to work fine to me.

**Comment by yrodiere** [comment]
> I've tested it with the quarkus quickstart, isn't it enough?

It is, but I only ready that you did (in the Quarkus issue) after posting this.

Anyway, adding those tests would be nice, but is not urgent since this issue was apparently solved (again) in Reactive 2.0.

Thanks for looking into this.
